const $=s=>document.querySelector(s);const defaults={hunger:70,mood:85,energy:65,clean:80,streak:0,sessions:0,xp:0,level:1,outfit:"classic"};let S=JSON.parse(localStorage.getItem("jinxDeluxe")||"null")||defaults;let remain=1500,total=1500,running=false,mode="focus",iv=null;
function save(){localStorage.setItem("jinxDeluxe",JSON.stringify(S))}function clamp(x){return Math.max(0,Math.min(100,Math.round(x)))}function stats(){let a=[["🍴","Голод","hunger"],["♥","Настроение","mood"],["⚡","Энергия","energy"],["💧","Чистота","clean"]];$("#stats").innerHTML=a.map(([i,n,k])=>`<div class="stat"><div class="statrow"><span>${i} ${n}</span><b>${S[k]}%</b></div><div class="bar"><div class="fill" style="width:${S[k]}%;background:#9e66e8"></div></div></div>`).join("");$("#streak").textContent=S.streak;$("#sessions").textContent=S.sessions;$("#level").textContent=S.level}
function render(){stats();$("#timer").textContent=String(Math.floor(remain/60)).padStart(2,"0")+":"+String(remain%60).padStart(2,"0");document.querySelectorAll(".outfits button").forEach(b=>b.classList.toggle("active",b.dataset.outfit===S.outfit))}
function say(t){$("#speech").textContent=t;$("#bubble").textContent=t}
function act(k){if(k==="feed"){S.hunger=clamp(S.hunger+20);S.mood=clamp(S.mood+5);say("М-м! Вот это еда! ♥")}if(k==="play"){S.hunger=clamp(S.hunger-5);S.energy=clamp(S.energy-10);S.mood=clamp(S.mood+18);say("Ха! Ещё раз!")}if(k==="rest"){S.energy=clamp(S.energy+25);S.mood=clamp(S.mood+5);say("Zzz... не шумите.")}save();render()}
function food(n){S.hunger=clamp(S.hunger+n);S.mood=clamp(S.mood+4);save();say("Спасибо! Ещё!");render()}
document.querySelectorAll(".outfits button").forEach(b=>b.onclick=()=>{S.outfit=b.dataset.outfit;save();render();say("Неплохо выгляжу, да?")});
document.querySelectorAll(".modes button").forEach(b=>b.onclick=()=>{if(running)return;total=+b.dataset.min*60;remain=total;document.querySelectorAll(".modes button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");render()});
$("#start").onclick=()=>{if(running){clearInterval(iv);running=false;$("#start").textContent="▶ Продолжить";return}running=true;$("#start").textContent="Ⅱ Пауза";say(mode==="focus"?"Фокусируемся вместе. Не отвлекайся. ♥":"Отдыхай, ты заслужил.");iv=setInterval(()=>{remain--;render();if(remain<=0){clearInterval(iv);running=false;if(mode==="focus"){S.sessions++;S.streak++;S.xp+=45;S.mood=clamp(S.mood+15);S.energy=clamp(S.energy-5);if(S.xp>=S.level*100){S.xp-=S.level*100;S.level++;say("Новый уровень! Ты крутой. ⭐")}else say("Готово! Ещё одна победа. ♥");mode="break";remain=300;total=300}else{mode="focus";remain=1500;total=1500;say("Перерыв окончен. Погнали снова!")}save();$("#start").textContent="▶ Начать";render()}},1000)};
$("#reset").onclick=()=>{clearInterval(iv);running=false;remain=total;$("#start").textContent="▶ Начать";render()};setInterval(()=>{if(!running){S.hunger=clamp(S.hunger-1);S.energy=clamp(S.energy-1);S.clean=clamp(S.clean-1);save();render()}},60000);render();